/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Zadanie2;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.IOException;
import java.io.OutputStream;
import java.io.OutputStreamWriter;
import java.io.Writer;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.JOptionPane;

/**
 *
 * @author Kamil Zemczak
 */
public class KsiazkaAdresowa extends javax.swing.JFrame {
    private ArrayList<Osoba> ksiazkaAdresowa = new ArrayList<Osoba>();
    private final File file = new File(System.getProperty("user.dir") + "/ksiazkaAdresowa.txt");
    /**
     * Creates new form AddressBook
     */
    public KsiazkaAdresowa() {
        initComponents();
        ladujKsiazkaAdresowa();
        pokazKsiazkaAdresowa();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nowaOsobaForm = new javax.swing.JFrame();
        jLabel6 = new javax.swing.JLabel();
        MastoField = new javax.swing.JTextField();
        ImieField = new javax.swing.JTextField();
        AnulujButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        OKButton = new javax.swing.JButton();
        UlicaField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        DomField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        KodPocztowyField1 = new javax.swing.JTextField();
        NazwiskoField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        KodPocztowyField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tekstArea = new javax.swing.JTextArea();
        DodajButton = new javax.swing.JButton();
        SortButton = new javax.swing.JButton();
        ZapisButton = new javax.swing.JButton();

        nowaOsobaForm.setMinimumSize(new java.awt.Dimension(360, 300));
        nowaOsobaForm.setPreferredSize(new java.awt.Dimension(360, 300));

        jLabel6.setText("Imię");

        AnulujButton.setText("Anuluj");
        AnulujButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anulujActionPerformed(evt);
            }
        });

        jLabel7.setText("Ulica:");

        OKButton.setText("Dodaj");
        OKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Nr domu:");

        jLabel2.setText("Kod pocztowy:");

        jLabel3.setText("Nazwisko:");

        jLabel4.setText("-");

        jLabel5.setText("Miejscowość:");

        javax.swing.GroupLayout newPersonFormLayout = new javax.swing.GroupLayout(nowaOsobaForm.getContentPane());
        nowaOsobaForm.getContentPane().setLayout(newPersonFormLayout);
        newPersonFormLayout.setHorizontalGroup(
            newPersonFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newPersonFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(newPersonFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(OKButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newPersonFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newPersonFormLayout.createSequentialGroup()
                        .addGroup(newPersonFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MastoField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(newPersonFormLayout.createSequentialGroup()
                                .addComponent(KodPocztowyField1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(KodPocztowyField2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(DomField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UlicaField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ImieField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NazwiskoField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(23, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newPersonFormLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(AnulujButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        newPersonFormLayout.setVerticalGroup(
            newPersonFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newPersonFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(newPersonFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(NazwiskoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newPersonFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ImieField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newPersonFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(UlicaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newPersonFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(DomField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newPersonFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(KodPocztowyField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(KodPocztowyField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newPersonFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(MastoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newPersonFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AnulujButton)
                    .addComponent(OKButton))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tekstArea.setEditable(false);
        tekstArea.setColumns(20);
        tekstArea.setLineWrap(true);
        tekstArea.setRows(5);
        jScrollPane1.setViewportView(tekstArea);

        DodajButton.setText("Dodaj");
        DodajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodajActionPerformed(evt);
            }
        });

        SortButton.setText("Sortuj");
        SortButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortActionPerformed(evt);
            }
        });

        ZapisButton.setText("Zapisz");
        ZapisButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DodajButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SortButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ZapisButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(DodajButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SortButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ZapisButton)
                        .addGap(0, 340, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        nowaOsobaForm.setVisible(true);
    }//GEN-LAST:event_addActionPerformed

    private void anulujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        nowaOsobaForm.dispose();
    }//GEN-LAST:event_cancelActionPerformed

    private void OKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKButtonActionPerformed
        if(!NazwiskoField.getText().isEmpty() &&
                !ImieField.getText().isEmpty() &&
                !UlicaField.getText().isEmpty() &&
                !DomField.getText().isEmpty() &&
                !KodPocztowyField1.getText().isEmpty() &&
                !KodPocztowyField2.getText().isEmpty() &&
                !MastoField.getText().isEmpty()){
            ksiazkaAdresowa.add(new Osoba(NazwiskoField.getText(), 
                    ImieField.getText(), 
                    UlicaField.getText(), 
                    DomField.getText(), 
                    KodPocztowyField1.getText() + "-" + KodPocztowyField2.getText(), 
                    MastoField.getText()));
            nowaOsobaForm.dispose();
            pokazKsiazkaAdresowa();
        }
        else
            JOptionPane.showMessageDialog(rootPane, "Proszę wypełnić pola formularza.");
    }//GEN-LAST:event_OKButtonActionPerformed

    private void sortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortActionPerformed
        MyComparator myCmp = new MyComparator();
        Collections.sort(ksiazkaAdresowa, myCmp);
        pokazKsiazkaAdresowa();
    }//GEN-LAST:event_sortActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        String daneDoZapisu = "";
        
        for(Osoba osoba:ksiazkaAdresowa)
            daneDoZapisu += osoba.getDaneDoZapisu() + System.lineSeparator();
        
        try{
            OutputStream outputStream = new FileOutputStream(file);
            Writer outputStreamWriter = new OutputStreamWriter(outputStream);
            outputStreamWriter.write(daneDoZapisu);
            outputStreamWriter.close();
        }catch(Exception ex){}
    }//GEN-LAST:event_saveActionPerformed

    private void pokazKsiazkaAdresowa(){
        String wszystkieDane = "";
        
        for(Osoba osoba:ksiazkaAdresowa)
            wszystkieDane += osoba.getSformatowaneDane() + System.lineSeparator();
        
        tekstArea.setText(wszystkieDane);
    }
    
    private void ladujKsiazkaAdresowa(){
        String line;
        try {
            BufferedReader buffReader = new BufferedReader(new FileReader(file));
            
            while((line = buffReader.readLine()) != null){
                ksiazkaAdresowa.add(Osoba.getOsobaFromString(line));
            }
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(rootPane, "Nie odnaleziono pliku.");
        } catch(IOException ex) {
            JOptionPane.showMessageDialog(rootPane, "Błąd odczytu pliku.");
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KsiazkaAdresowa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KsiazkaAdresowa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KsiazkaAdresowa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KsiazkaAdresowa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KsiazkaAdresowa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OKButton;
    private javax.swing.JButton DodajButton;
    private javax.swing.JButton AnulujButton;
    private javax.swing.JTextField MastoField;
    private javax.swing.JTextField DomField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField ImieField;
    private javax.swing.JFrame nowaOsobaForm;
    private javax.swing.JTextField KodPocztowyField1;
    private javax.swing.JTextField KodPocztowyField2;
    private javax.swing.JButton ZapisButton;
    private javax.swing.JButton SortButton;
    private javax.swing.JTextField UlicaField;
    private javax.swing.JTextField NazwiskoField;
    private javax.swing.JTextArea tekstArea;
    // End of variables declaration//GEN-END:variables
}
